"""empty message

Revision ID: 0b33aae22264
Revises: f2e5e71d56e3
Create Date: 2025-05-31 10:12:33.193479
"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '0b33aae22264'
down_revision = 'f2e5e71d56e3'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('cpf_cnpj', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint('uq_user_cpf_cnpj', ['cpf_cnpj'])  # Nome da constraint adicionado

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_cpf_cnpj', type_='unique')  # Nome da constraint deve ser o mesmo
        batch_op.drop_column('cpf_cnpj')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
