"""empty message

Revision ID: 28b7dff10867
Revises: a70fb7a678ba
Create Date: 2025-06-04 11:23:35.984844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b7dff10867'
down_revision = 'a70fb7a678ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguidores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguidores',
    sa.Column('seguidor_id', sa.INTEGER(), nullable=True),
    sa.Column('seguido_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['seguido_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seguidor_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
