"""empty message

Revision ID: 511f3f9d920b
Revises: 
Create Date: 2025-06-04 10:06:15.688726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '511f3f9d920b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('sobreNome', sa.String(length=150), nullable=True),
    sa.Column('status', sa.String(length=150), nullable=True),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('senha', sa.String(length=150), nullable=False),
    sa.Column('imagem', sa.String(length=150), nullable=True),
    sa.Column('cor_fundo', sa.String(length=255), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remetente_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('editada', sa.Boolean(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=True),
    sa.Column('remetente_id', sa.Integer(), nullable=True),
    sa.Column('mensagem', sa.String(length=255), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['remetente_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacao')
    op.drop_table('mensagem')
    op.drop_table('followers')
    op.drop_table('user')
    # ### end Alembic commands ###
