"""empty message

Revision ID: 548728a7e7e8
Revises: 856f80872e7b
Create Date: 2025-05-28 07:00:33.064426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548728a7e7e8'
down_revision = '856f80872e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('sobreNome', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('senha', sa.VARCHAR(length=255), nullable=False),
    sa.Column('imagem', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
