"""empty message

Revision ID: 856f80872e7b
Revises: 0bb047f35aba
Create Date: 2025-05-28 06:41:39.757947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856f80872e7b'
down_revision = '0bb047f35aba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
