"""empty message

Revision ID: 85c255af9697
Revises: f47ec4bb0db5
Create Date: 2025-06-02 05:35:52.891942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c255af9697'
down_revision = 'f47ec4bb0db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criada_em', sa.DateTime(), nullable=True))
        batch_op.alter_column('mensagem',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacao', schema=None) as batch_op:
        batch_op.alter_column('mensagem',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('criada_em')

    # ### end Alembic commands ###
