"""empty message

Revision ID: 86bd37c0a9ef
Revises: 91ad5d732486
Create Date: 2025-05-31 09:43:01.032345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86bd37c0a9ef'
down_revision = '91ad5d732486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('cpf_cnpj', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint("uq_user_cpf_cnpj", ['cpf_cnpj'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint("uq_user_cpf_cnpj", type_='unique')
        batch_op.drop_column('cpf_cnpj')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
