"""empty message

Revision ID: a70fb7a678ba
Revises: fbdd0c6e5686
Create Date: 2025-06-04 11:06:35.883718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a70fb7a678ba'
down_revision = 'fbdd0c6e5686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seguidores',
    sa.Column('seguidor_id', sa.Integer(), nullable=True),
    sa.Column('seguido_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seguido_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['seguidor_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seguidores')
    # ### end Alembic commands ###
