"""empty message

Revision ID: b4c4804e2d19
Revises: 05f5d9c21ac6
Create Date: 2025-05-30 07:18:22.082547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c4804e2d19'
down_revision = '05f5d9c21ac6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=True)
        batch_op.alter_column('sobreNome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=150),
               nullable=True)
        batch_op.alter_column('senha',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=150),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('senha',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('sobreNome',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
