"""empty message

Revision ID: f2e5e71d56e3
Revises: 86bd37c0a9ef
Create Date: 2025-05-31 09:59:07.101228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2e5e71d56e3'
down_revision = '86bd37c0a9ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_cpf_cnpj'), type_='unique')
        batch_op.drop_column('status')
        batch_op.drop_column('cpf_cnpj')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf_cnpj', sa.VARCHAR(length=150), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=150), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_user_cpf_cnpj'), ['cpf_cnpj'])

    # ### end Alembic commands ###
