"""empty message

Revision ID: f47ec4bb0db5
Revises: e035987d02b1
Create Date: 2025-06-02 05:16:10.919945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f47ec4bb0db5'
down_revision = 'e035987d02b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor_fundo', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('cor_fundo')

    # ### end Alembic commands ###
