"""empty message

Revision ID: fbdd0c6e5686
Revises: 511f3f9d920b
Create Date: 2025-06-04 10:14:56.310824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbdd0c6e5686'
down_revision = '511f3f9d920b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))
        batch_op.drop_column('ultimo_acesso')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_acesso', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_seen')

    # ### end Alembic commands ###
